version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      #- sudo apt-get install -y python3-venv
      - python3.9 -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      #- pip install .
      - pip install -r req.txt
      - rm -rf dspt
      - mkdir test-reports
  build:
    commands:
      - pytest 
        --html=test-reports/report.html 
        --self-contained-html
        -s
        -v
        --cov=dspt 
        --cov-report=html:test-reports/coverage 
        --junitxml=test-reports/junit.xml 
        --log-file=test-reports/logs.txt 
        tests
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  coverage:
    files:
      - "coverage/*"
    base-directory: 'test-reports'
    discard-paths: yes
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml